### ISSUE TITLE
Спроектировать схему базы данных

### ISSUE THREAD

**Issue by lbdlbdlbdl** [edu-xored/jogging-app#1]

**Comment by itfobos** [comment]
Причём сделать это в виде файла-скрипта(или типа того). 
Основной момент, чтобы мы могли это безболезнено повторить ещё раз, если понадобится

По хорошему ,сделать папке `db` в проекте, туду положить `redme.md` файл, где написать как развернуть базу с нуля. 
Тут можно посоветоваться с тех-писателем как это лучше делать.

**Comment by itfobos** [comment]
@asgeneral Предоставь Алисе доступ до проекта в firebase, который ты создал.

**Comment by lbdlbdlbdl** [comment]
- [x] Добавить файл-скрипт
- [x] Сделать readme.md файл
