### ISSUE TITLE
Разобраться с публикацией фронтенда в GitHub Pages

### ISSUE THREAD

**Issue by itfobos** [edu-xored/jogging-app#10]
Разобраться как это делается
Опубликовать текущую сборку

Критерии выполненности задачи :
- Есть URL, куда можно зайти и посмотреть на наш фронт
- В соответствующей ветке , есть ридмишка, где написано как это сделать.

**Comment by itfobos** [comment]
Сделал ветку, включил что надо в админке.

Наш URL: https://edu-xored.github.io/jogging-app/

**Comment by bondiano** [comment]
DONE https://joggingapp.github.io/login
