### ISSUE TITLE
Сделать модель Record

### ISSUE THREAD

**Issue by lbdlbdlbdl** [edu-xored/jogging-app#16]
Сделать модель Record. Посмотреть поля в документации (ТЗ). Иметь в виду, что поля немодифицируемые извне и присутствует ссылка на userId.

**Comment by itfobos** [comment]
@lbdlbdlbdl Былоб круто ссылки на документацию(больше конкретики) + упомянуть что мы immutable модельки делаем.

**Comment by lbdlbdlbdl** [comment]
It was solved in PR#12.
