### ISSUE TITLE
Routing

### ISSUE THREAD

**Issue by lbdlbdlbdl** [edu-xored/jogging-app#2]
В рамках задачи , добавить один компонент - login, оставить его без изменений.

Добавить роутинг на этот компонент `/login`

Критерий завершённости задачи:
Пользователь отрывает `localhost:4200/login` и видит _login works_

**Comment by lbdlbdlbdl** [comment]
@bondiano

**Comment by bondiano** [comment]
@lbdlbdlbdl

**Comment by itfobos** [comment]
@bondiano Чекай новое описание задачи.

**Comment by bondiano** [comment]
Done
