### ISSUE TITLE
Mark up the Login page at LoginComponent.

### ISSUE THREAD

**Issue by lbdlbdlbdl** [edu-xored/jogging-app#24]
Use `userService`.
Use material design.

**Comment by itfobos** [comment]
Что-то типа того:
 - Ссылку для создания акка - не надо
- Вместо логина по email - github

![screenshot from 2018-02-01 18-50-45](https://user-images.githubusercontent.com/3685726/35677094-eaaa148a-0780-11e8-810e-cb5c64f568b8.png)

**Comment by bondiano** [comment]
DONE
