### ISSUE TITLE
ReportsComponent: сверстать страницу, содержащую таблицу с записями, в стиле Material

### ISSUE THREAD

**Issue by lbdlbdlbdl** [edu-xored/jogging-app#31]
Страница должна содержать:

- Таблицу с записями (поля см. в [документации](https://drive.google.com/file/d/1c8QwXbZLTrS7EhX_kMVsxkLoEArMqk3M/view?usp=sharing)

- Кнопку "удалить" после каждой записи в таблице

- Кнопку "добавить новый рекорд" справа от таблицы

**Comment by bondiano** [comment]
DONE
