### ISSUE TITLE
Add pages header

### ISSUE THREAD

**Issue by bondiano** [edu-xored/jogging-app#7]
Добавить общую "шапку" для всех страниц приложения.
В шапке должно быть лого (название JoggingApp) проекта и кнопка, меняющаяся в зависимости от текущего состояния пользователя:

- Если пользователь не авторизован - _Login_
- Если пользователь авторизован - _Имя пользователя_ +  _Logout_

![screenshot from 2018-01-28 23-06-17](https://user-images.githubusercontent.com/3685726/35484248-0a6e759e-0480-11e8-8bb1-181fb7466ab7.png)

**Comment by lbdlbdlbdl** [comment]
Подойдет toolbar из material design. Чтобы подключить material, в `app.module.ts` нужно подключить нужные Material модули.

_Информация:_
https://material.angular.io/components/toolbar/overview
https://material.angularjs.org/latest/demo/toolbar

**Comment by itfobos** [comment]
Icons pack https://fontawesome.com

**Comment by itfobos** [comment]
@bondiano @asgeneral 
Я тут ещё подумал: кнопку 'Signin' наверное нету смысла показываться вообще.

Если пользователь зашёл на какую-то приватную страницу незалогиненым, то перекидывать его на логинку.

Т..е поведение такое:
- Если авторизован , показываем кнопку Logout
- Если не авторизован, никакую кнопку не показываем.

**Comment by bondiano** [comment]
DONE
