### ISSUE TITLE
Make appropriate favicon

### ISSUE THREAD

**Issue by itfobos** [edu-xored/jogging-app#9]
Now we have Angular logo, as icon on a browser tab. 
![screenshot from 2018-01-30 13-05-15](https://user-images.githubusercontent.com/3685726/35550704-3afdf024-05be-11e8-9c28-6574be8012f0.png)

Lets make something corresponding for our project.

**Comment by itfobos** [comment]
@asgeneral @lbdlbdlbdl 

Открываешь задачу : нет ни одного свзанного коммита, соответствующий PR не вмёржен.

Задачу закрывать есть смысл, когда код уже в мастер попал.

**Comment by itfobos** [comment]
@asgeneral @lbdlbdlbdl 

Открываешь задачу : нет ни одного свзанного коммита, соответствующий PR не вмёржен, статус "закрыто"(без коментариев) - не надо так.

Задачу закрывать есть смысл, когда код уже в мастер попал.

**Comment by asgeneral** [comment]
@itfobos Это не моя прихоть, я просто не знаю как все делается на гите, весь вечер искал как сделать pull request, там было сказано что реквест подал и все, мастер или принимает или нет сам, от тебя это не зависит, про оформление комита ветки и т.д. все понял
